export const sampleMovies = [
{
      averageRating: 6.7,
      budget: 200000000,
      contentRating: "PG",
      countriesOfOrigin: ["US", "CA"],
      description:
        "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
      genres: ["Adventure", "Animation", "Drama"],
      grossWorldwide: 366713966,
      primaryImage:
        "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
      primaryTitle: "Mufasa: The Lion King",
      releaseDate: "2024-12-20",
      runtimeMinutes: 118,
      spokenLanguages: ["en"],
      url: "https://www.imdb.com/title/tt13186482/",
    },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },{
        averageRating: 6.7,
        budget: 200000000,
        contentRating: "PG",
        countriesOfOrigin: ["US", "CA"],
        description:
          "Mufasa, a cub lost and alone, meets a sympathetic lion named Taka, the heir to a royal bloodline. The chance meeting sets in motion an expansive journey of a group of misfits searching for their destiny.",
        genres: ["Adventure", "Animation", "Drama"],
        grossWorldwide: 366713966,
        primaryImage:
          "https://m.media-amazon.com/images/M/MV5BYjBkOWUwODYtYWI3YS00N2I0LWEyYTktOTJjM2YzOTc3ZDNlXkEyXkFqcGc@._V1_.jpg",
        primaryTitle: "Mufasa: The Lion King",
        releaseDate: "2024-12-20",
        runtimeMinutes: 118,
        spokenLanguages: ["en"],
        url: "https://www.imdb.com/title/tt13186482/",
      },
    // Add more movie objects here if needed
  ];